[main]
font=JetBrainsMono Nerd Font:size=10

[colors-dark]
alpha=0.8

foreground=F2F2F2
background=242827

# Normal ANSI colors
regular0=10261E
regular1=A6212C
regular2=A69F44
regular3=BF5934
regular4=BF5934
regular5=8C711F
regular6=A69F44
regular7=F2F2F2

# Bright ANSI colors
bright0=8C711F
bright1=BF5934
bright2=A69F44
bright3=F2F2F2
bright4=F2F2F2
bright5=A69F44
bright6=F2F2F2
bright7=F2F2F2

